/// Autogenerated on 17/03/2024 12:31:43 by Vinyl Editor 6.0.0, 2024-03-14

function __VinylGenPlay()
{
    static _data = undefined;
    
    if (_data == undefined)
    {
        _data = {};
        
    }
    
    return _data;
}

