/// Autogenerated on 2024-03-21 21:35:28 by Vinyl Editor 6.0.0, 2024-03-14

function __VinylGenPlay()
{
    static _data = undefined;
    
    if (_data == undefined)
    {
        _data = {};
        
        struct_set_from_hash(_data, vinrhrht, function(_loop, _gainLocal, _pitchLocal)
        {
            return -1;
        });

        struct_set_from_hash(_data, vinFootsteps, function(_loop, _gainLocal, _pitchLocal)
        {
            return -1;
        });

        struct_set_from_hash(_data, vinLoopingTrack, function(_loop_UNUSED, _gainLocal, _pitchLocal)
        {
            static _pattern = struct_get_from_hash(__VinylGenPattern(), vinLoopingTrack);
            return (new __VinylClassVoiceHLT(_pattern)).__currentVoice;
        });

    }
    
    return _data;
}

