/// Autogenerated on 2024-03-18 21:52:56 by Vinyl Editor 6.0.0, 2024-03-14

function __VinylGenPlay()
{
    static _data = undefined;
    
    if (_data == undefined)
    {
        _data = {};
        
        struct_set_from_hash(_data, vinrhrht, function(_loop, _gainLocal, _pitchLocal)
        {
            return -1;
        });

        struct_set_from_hash(_data, vinFootsteps, function(_loop, _gainLocal, _pitchLocal)
        {
            static _soundArray = [sndBleep0, sndBleep1, sndBleep2, sndBleep3, sndBleep4];
            static _playIndex = infinity;
            
            if (_playIndex >= 5) //If we've played through our bank of sounds, reshuffle
            {
                _playIndex = 0;
                var _last = _soundArray[4];
                array_delete(_soundArray, 4, 1); //Make sure we don't reshuffle in the last played sound...
                __VinylArrayShuffle(_soundArray);
                array_insert(_soundArray, 2, _last); //...and stick it somewhere in the middle instead
            }
            
            var _sound = _soundArray[_playIndex];
            ++_playIndex;
            
            var _gainPattern  = 1;
            var _pitchPattern = 1;
            var _voice = audio_play_sound(_sound, 0, false, _gainLocal*_gainPattern, 0, _pitchLocal*_pitchPattern);
            
            if (VINYL_LIVE_EDIT)
            {
                __VinylVoiceTrack(_voice, _gainLocal, _pitchLocal, _gainPattern, _pitchPattern).__pattern = vinFootsteps;
            }
            else
            {
                __VinylVoiceTrack(_voice, _gainLocal, _pitchLocal, _gainPattern, _pitchPattern);
            }
            
            return _voice;
        });

    }
    
    return _data;
}

