/// Autogenerated on 2024-03-21 21:35:28 by Vinyl Editor 6.0.0, 2024-03-14

function __VinylGenPatternNames()
{
    static _data = undefined;
    
    if (_data == undefined)
    {
        _data = {};
        
        _data[$ "vinrhrht"] = vinrhrht;
        _data[$ "vinFootsteps"] = vinFootsteps;
        _data[$ "vinLoopingTrack"] = vinLoopingTrack;
    }
    
    return _data;
}

