/// Autogenerated on 2024-03-21 21:35:28 by Vinyl Editor 6.0.0, 2024-03-14

function __VinylGenPattern()
{
    static _data = undefined;
    
    if (_data == undefined)
    {
        _data = {};
        
        struct_set_from_hash(_data, vinLoopingTrack, new __VinylClassPatternHLT(vinLoopingTrack, sndBleep0, sndBleep1, sndBleep2, false, 1));
    }
    
    return _data;
}

