/// Autogenerated on 2024-03-17 22:11:08 by Vinyl Editor 6.0.0, 2024-03-14

function __VinylGenPattern()
{
    static _data = undefined;
    
    if (_data == undefined)
    {
        _data = {};
        
    }
    
    return _data;
}

