/// Autogenerated on 2024-03-16 15:02:19 by Vinyl Editor 6.0.0, 2024-03-14

function __VinylGenPattern()
{
    static _data = undefined;
    
    if (_data == undefined)
    {
        _data = {};
        
        struct_set_from_hash(_data, int64(snd1KHz), new __VinylClassPatternSound(snd1KHz, false, 1, 1, 0.63, 0.63));

    }
    
    return _data;
}

