/// Autogenerated on 2024-03-24 17:07:04 by Vinyl Editor 6.0.0, 2024-03-14
#macro VINYL_VERSIONED_IDENT  "002B13F0BAD8EFBA"

//Patterns
#macro vinrhrht  0x43F498AF_00000001
#macro vinFootsteps  0x43F498AF_00000002
#macro vinLoopingTrack  0x43F498AF_00000003
#macro vinBlendTest  0x43F498AF_00000004
