/// Autogenerated on 16/03/2024 12:12:18 by Vinyl Editor 6.0.0, 2024-03-14

function __VinylGenPlay()
{
    static _data = undefined;
    
    if (_data == undefined)
    {
        _data = {};
        
        struct_set_from_hash(_data, int64(snd1KHz), function(_loop, _gainMultiplier, _pitchMultiplier)
        {
            var _gainFinal = _gainMultiplier;
            var _pitchFinal = _pitchMultiplier*0.63;
            var _voice = audio_play_sound(snd1KHz, 0, _loop ?? false, _gainFinal, 0, _pitchFinal);
            __VinylVoiceTrack(_voice, _gainMultiplier, _gainFinal, _pitchMultiplier, _pitchFinal);
            return _voice;
        });

    }
    
    return _data;
}

