/// Autogenerated on 2024-03-15 23:13:15 by Vinyl Editor 6.0.0, 2024-03-14

function Vinyl_snd1KHz()
{
    return audio_play_sound(snd1KHz, 1, false, 1.27, 0, 0.53);
}

function Vinyl_VinylFallbackSound()
{
    return audio_play_sound(VinylFallbackSound, 1, false);
}

function Vinyl_sndBleep0()
{
    return audio_play_sound(sndBleep0, 1, false, 0.77, 0, 1.17);
}

function Vinyl_sndBleep1()
{
    return audio_play_sound(sndBleep1, 1, false);
}

function Vinyl_sndBleep10()
{
    return audio_play_sound(sndBleep10, 1, false);
}

function Vinyl_sndBleep11()
{
    return audio_play_sound(sndBleep11, 1, false);
}

function Vinyl_sndBleep2()
{
    return audio_play_sound(sndBleep2, 1, false);
}

function Vinyl_sndBleep3()
{
    return audio_play_sound(sndBleep3, 1, false);
}

function Vinyl_sndBleep4()
{
    return audio_play_sound(sndBleep4, 1, false);
}

function Vinyl_sndBleep5()
{
    return audio_play_sound(sndBleep5, 1, false);
}

function Vinyl_sndBleep6()
{
    return audio_play_sound(sndBleep6, 1, false);
}

function Vinyl_sndBleep7()
{
    return audio_play_sound(sndBleep7, 1, false);
}

function Vinyl_sndBleep8()
{
    return audio_play_sound(sndBleep8, 1, false);
}

function Vinyl_sndBleep9()
{
    return audio_play_sound(sndBleep9, 1, false);
}

function Vinyl_sndBonk()
{
    return audio_play_sound(sndBonk, 1, false);
}

function Vinyl_sndCat()
{
    return audio_play_sound(sndCat, 1, false);
}

function Vinyl_sndChickenNuggets()
{
    return audio_play_sound(sndChickenNuggets, 1, false);
}

function Vinyl_sndOw()
{
    return audio_play_sound(sndOw, 1, false);
}

function Vinyl_sndPop()
{
    return audio_play_sound(sndPop, 1, false);
}

function Vinyl_sndSync0()
{
    return audio_play_sound(sndSync0, 1, false);
}

function Vinyl_sndSync1()
{
    return audio_play_sound(sndSync1, 1, false);
}

function Vinyl_sndSync2()
{
    return audio_play_sound(sndSync2, 1, false);
}

function Vinyl_sndSync3()
{
    return audio_play_sound(sndSync3, 1, false);
}

