/// Autogenerated on 16/03/2024 12:08:58 by Vinyl Editor 6.0.0, 2024-03-14

function __VinylGenPlay()
{
    static _data = undefined;
    
    if (_data == undefined)
    {
        _data = {};
    }
    
    return _data;
}

